### ISSUE TITLE
Error running `1-bird-migration` notebook on mybinder

### ISSUE THREAD

**Issue by brl0** [anitagraser/movingpandas-examples#3] opened 2021-03-10 15:30 UTC
First, I really appreciate the great project and examples you have put together.

When I tried running the `1-bird-migration` notebook on mybinder, the following error occurs in cell 20:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-20-52e63e9e0a94> in <module>
----> 1 arrivals = [traj for traj in my_traj.clip(area_of_interest)]
      2 print("Found {} arrivals".format(len(arrivals)))
      3 
      4 for traj in arrivals:
      5     print("Individual '{}' arrived at {}".format(traj.df['individual-local-identifier'].iloc[0], traj.get_start_time()))

/srv/conda/envs/notebook/lib/python3.7/site-packages/movingpandas/trajectory.py in clip(self, polygon, pointbased)
    643             Clipped trajectory segments
    644         """
--> 645         return clip(self, polygon, pointbased)
    646 
    647     def intersection(self, feature, pointbased=False):

/srv/conda/envs/notebook/lib/python3.7/site-packages/movingpandas/overlay.py in clip(traj, polygon, pointbased)
    169         ranges = _determine_time_ranges_pointbased(traj, polygon)
    170     else:
--> 171         ranges = _determine_time_ranges_linebased(traj, polygon)
    172     return _get_segments_for_ranges(traj, ranges)
    173 

/srv/conda/envs/notebook/lib/python3.7/site-packages/movingpandas/overlay.py in _determine_time_ranges_linebased(traj, polygon)
    155     possible_matches = _get_potentially_intersecting_lines(traj, polygon)
    156     possible_matches['spatial_intersection'] = possible_matches.intersection(polygon)
--> 157     possible_matches['spatiotemporal_intersection'] = possible_matches.apply(_get_spatiotemporal_ref, axis=1)
    158     ranges = possible_matches['spatiotemporal_intersection']
    159     return _dissolve_ranges(ranges)

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/frame.py in apply(self, func, axis, raw, result_type, args, **kwds)
   7763             kwds=kwds,
   7764         )
-> 7765         return op.get_result()
   7766 
   7767     def applymap(self, func, na_action: Optional[str] = None) -> DataFrame:

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/apply.py in get_result(self)
    183             return self.apply_raw()
    184 
--> 185         return self.apply_standard()
    186 
    187     def apply_empty_result(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/apply.py in apply_standard(self)
    274 
    275     def apply_standard(self):
--> 276         results, res_index = self.apply_series_generator()
    277 
    278         # wrap results

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/apply.py in apply_series_generator(self)
    288             for i, v in enumerate(series_gen):
    289                 # ignore SettingWithCopy here in case the user mutates
--> 290                 results[i] = self.f(v)
    291                 if isinstance(results[i], ABCSeries):
    292                     # If we have a view on v, we need to make a copy because

/srv/conda/envs/notebook/lib/python3.7/site-packages/movingpandas/overlay.py in _get_spatiotemporal_ref(row)
     14     """
     15     if type(row['spatial_intersection']) == LineString:
---> 16         pt0 = Point(row['spatial_intersection'].coords[0])
     17         ptn = Point(row['spatial_intersection'].coords[-1])
     18         t = row['prev_t']

IndexError: list index out of range
```

**Comment by anitagraser** [comment] 2021-03-10 16:03
Thank you for reporting, Brian! Looks like a new one. I'll investigate.

**Comment by anitagraser** [comment] 2021-03-10 17:56
MyBinder seems to use Geopandas 0.8.2 currently. On my local system, using Geopandas 0.9.0, I cannot reproduce the issue so far.

**Comment by anitagraser** [comment] 2021-03-10 18:36
I committed some minor changes to the repo to for MyBinder to build a new environment. It now uses GeoPandas 0.9.0 and the error is gone.

**Closed by anitagraser** 2021-03-10 18:36 UTC
Labels: bug
